!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitMOD_dataSpec_P5B(f2pysetupfunc)
      use MOD_dataSpec_P5B, only : k_Cm
      use MOD_dataSpec_P5B, only : i
      use MOD_dataSpec_P5B, only : k_Car
      use MOD_dataSpec_P5B, only : refractive
      use MOD_dataSpec_P5B, only : Rsoil2
      use MOD_dataSpec_P5B, only : Rsoil1
      use MOD_dataSpec_P5B, only : k_Brown
      use MOD_dataSpec_P5B, only : Ed
      use MOD_dataSpec_P5B, only : k_Cw
      use MOD_dataSpec_P5B, only : k_Cab
      use MOD_dataSpec_P5B, only : lambda
      use MOD_dataSpec_P5B, only : Es
      use MOD_dataSpec_P5B, only : nw
      external f2pysetupfunc
      call f2pysetupfunc(k_Cm,i,k_Car,refractive,Rsoil2,Rsoil1,k_Brown,E&
     &d,k_Cw,k_Cab,lambda,Es,nw)
      end subroutine f2pyinitMOD_dataSpec_P5B

      
      subroutine f2pyinitMOD_ANGLE(f2pysetupfunc)
      use MOD_ANGLE, only : rd
      use MOD_ANGLE, only : pi
      external f2pysetupfunc
      call f2pysetupfunc(rd,pi)
      end subroutine f2pyinitMOD_ANGLE

      subroutine f2py_MOD_staticvar_getdims_vb(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => vb

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_vb
      subroutine f2py_MOD_staticvar_getdims_vf(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => vf

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_vf
      subroutine f2py_MOD_staticvar_getdims_lidf(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => lidf

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_lidf
      subroutine f2py_MOD_staticvar_getdims_m(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => m

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_m
      subroutine f2py_MOD_staticvar_getdims_sigb(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => sigb

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_sigb
      subroutine f2py_MOD_staticvar_getdims_sb(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => sb

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_sb
      subroutine f2py_MOD_staticvar_getdims_rinf(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => rinf

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_rinf
      subroutine f2py_MOD_staticvar_getdims_sf(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => sf

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_sf
      subroutine f2py_MOD_staticvar_getdims_att(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => att

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_att
      subroutine f2py_MOD_staticvar_getdims_w(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => w

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_w
      subroutine f2py_MOD_staticvar_getdims_m2(r,s,f2pysetdata,flag)
      use MOD_staticvar, only: d => m2

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_staticvar_getdims_m2
      
      subroutine f2pyinitMOD_staticvar(f2pysetupfunc)
      use MOD_staticvar, only : vb
      use MOD_staticvar, only : sob
      use MOD_staticvar, only : vf
      use MOD_staticvar, only : sof
      use MOD_staticvar, only : dof
      use MOD_staticvar, only : lidf
      use MOD_staticvar, only : m
      use MOD_staticvar, only : sdf
      use MOD_staticvar, only : sigb
      use MOD_staticvar, only : sdb
      use MOD_staticvar, only : sb
      use MOD_staticvar, only : rinf
      use MOD_staticvar, only : ctscto
      use MOD_staticvar, only : cts
      use MOD_staticvar, only : dob
      use MOD_staticvar, only : ko
      use MOD_staticvar, only : sf
      use MOD_staticvar, only : ks
      use MOD_staticvar, only : dso
      use MOD_staticvar, only : att
      use MOD_staticvar, only : w
      use MOD_staticvar, only : m2
      use MOD_staticvar, only : ddb
      use MOD_staticvar, only : sumint
      use MOD_staticvar, only : cto
      use MOD_staticvar, only : ddf
      external f2pysetupfunc
      external f2py_MOD_staticvar_getdims_vb
      external f2py_MOD_staticvar_getdims_vf
      external f2py_MOD_staticvar_getdims_lidf
      external f2py_MOD_staticvar_getdims_m
      external f2py_MOD_staticvar_getdims_sigb
      external f2py_MOD_staticvar_getdims_sb
      external f2py_MOD_staticvar_getdims_rinf
      external f2py_MOD_staticvar_getdims_sf
      external f2py_MOD_staticvar_getdims_att
      external f2py_MOD_staticvar_getdims_w
      external f2py_MOD_staticvar_getdims_m2
      call f2pysetupfunc(f2py_MOD_staticvar_getdims_vb,sob,f2py_MOD_stat&
     &icvar_getdims_vf,sof,dof,f2py_MOD_staticvar_getdims_lidf,f2py_MOD_&
     &staticvar_getdims_m,sdf,f2py_MOD_staticvar_getdims_sigb,sdb,f2py_M&
     &OD_staticvar_getdims_sb,f2py_MOD_staticvar_getdims_rinf,ctscto,cts&
     &,dob,ko,f2py_MOD_staticvar_getdims_sf,ks,dso,f2py_MOD_staticvar_ge&
     &tdims_att,f2py_MOD_staticvar_getdims_w,f2py_MOD_staticvar_getdims_&
     &m2,ddb,sumint,cto,ddf)
      end subroutine f2pyinitMOD_staticvar

      subroutine f2py_MOD_output_PROSPECT_getdims_tau(r,s,f2pysetdata,fl&
     &ag)
      use MOD_output_PROSPECT, only: d => tau

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_output_PROSPECT_getdims_tau
      subroutine f2py_MOD_output_PROSPECT_getdims_LRT(r,s,f2pysetdata,fl&
     &ag)
      use MOD_output_PROSPECT, only: d => LRT

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_output_PROSPECT_getdims_LRT
      subroutine f2py_MOD_output_PROSPECT_getdims_rho(r,s,f2pysetdata,fl&
     &ag)
      use MOD_output_PROSPECT, only: d => rho

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_output_PROSPECT_getdims_rho
      
      subroutine f2pyinitMOD_output_PROSPECT(f2pysetupfunc)
      use MOD_output_PROSPECT, only : tau
      use MOD_output_PROSPECT, only : LRT
      use MOD_output_PROSPECT, only : rho
      external f2pysetupfunc
      external f2py_MOD_output_PROSPECT_getdims_tau
      external f2py_MOD_output_PROSPECT_getdims_LRT
      external f2py_MOD_output_PROSPECT_getdims_rho
      call f2pysetupfunc(f2py_MOD_output_PROSPECT_getdims_tau,f2py_MOD_o&
     &utput_PROSPECT_getdims_LRT,f2py_MOD_output_PROSPECT_getdims_rho)
      end subroutine f2pyinitMOD_output_PROSPECT

      subroutine f2py_MOD_flag_util_getdims_rsoil_old(r,s,f2pysetdata,fl&
     &ag)
      use MOD_flag_util, only: d => rsoil_old

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_flag_util_getdims_rsoil_old
      subroutine f2py_MOD_flag_util_getdims_lidf_old(r,s,f2pysetdata,fla&
     &g)
      use MOD_flag_util, only: d => lidf_old

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_flag_util_getdims_lidf_old
      
      subroutine f2pyinitMOD_flag_util(f2pysetupfunc)
      use MOD_flag_util, only : rsoil_old
      use MOD_flag_util, only : delta_soil
      use MOD_flag_util, only : delta_skyl
      use MOD_flag_util, only : Cm_old
      use MOD_flag_util, only : delta_lidf
      use MOD_flag_util, only : Cab_old
      use MOD_flag_util, only : delta_lai
      use MOD_flag_util, only : psi_old
      use MOD_flag_util, only : tto_old
      use MOD_flag_util, only : LIDFa_old
      use MOD_flag_util, only : flag
      use MOD_flag_util, only : delta_geom
      use MOD_flag_util, only : N_old
      use MOD_flag_util, only : tts_old
      use MOD_flag_util, only : skyl_old
      use MOD_flag_util, only : init_completed0
      use MOD_flag_util, only : Car_old
      use MOD_flag_util, only : q_old
      use MOD_flag_util, only : Cw_old
      use MOD_flag_util, only : Cbrown_old
      use MOD_flag_util, only : init_completed
      use MOD_flag_util, only : delta_leaf
      use MOD_flag_util, only : LIDFb_old
      use MOD_flag_util, only : lidf_old
      use MOD_flag_util, only : delta_hot
      use MOD_flag_util, only : lai_old
      external f2pysetupfunc
      external f2py_MOD_flag_util_getdims_rsoil_old
      external f2py_MOD_flag_util_getdims_lidf_old
      call f2pysetupfunc(f2py_MOD_flag_util_getdims_rsoil_old,delta_soil&
     &,delta_skyl,Cm_old,delta_lidf,Cab_old,delta_lai,psi_old,tto_old,LI&
     &DFa_old,flag,delta_geom,N_old,tts_old,skyl_old,init_completed0,Car&
     &_old,q_old,Cw_old,Cbrown_old,init_completed,delta_leaf,LIDFb_old,f&
     &2py_MOD_flag_util_getdims_lidf_old,delta_hot,lai_old)
      end subroutine f2pyinitMOD_flag_util

      subroutine f2py_MOD_SAIL_getdims_rso(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rso

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rso
      subroutine f2py_MOD_SAIL_getdims_tdo(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => tdo

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_tdo
      subroutine f2py_MOD_SAIL_getdims_rsd(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rsd

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rsd
      subroutine f2py_MOD_SAIL_getdims_tdd(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => tdd

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_tdd
      subroutine f2py_MOD_SAIL_getdims_rsdt(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rsdt

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rsdt
      subroutine f2py_MOD_SAIL_getdims_rdot(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rdot

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rdot
      subroutine f2py_MOD_SAIL_getdims_rsodt(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rsodt

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rsodt
      subroutine f2py_MOD_SAIL_getdims_rsod(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rsod

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rsod
      subroutine f2py_MOD_SAIL_getdims_tso(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => tso

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_tso
      subroutine f2py_MOD_SAIL_getdims_rddt(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rddt

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rddt
      subroutine f2py_MOD_SAIL_getdims_rsost(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rsost

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rsost
      subroutine f2py_MOD_SAIL_getdims_tsd(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => tsd

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_tsd
      subroutine f2py_MOD_SAIL_getdims_rsot(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rsot

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rsot
      subroutine f2py_MOD_SAIL_getdims_rdd(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rdd

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rdd
      subroutine f2py_MOD_SAIL_getdims_rsos(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rsos

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rsos
      subroutine f2py_MOD_SAIL_getdims_rdo(r,s,f2pysetdata,flag)
      use MOD_SAIL, only: d => rdo

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_MOD_SAIL_getdims_rdo
      
      subroutine f2pyinitMOD_SAIL(f2pysetupfunc)
      use MOD_SAIL, only : rso
      use MOD_SAIL, only : tdo
      use MOD_SAIL, only : rsd
      use MOD_SAIL, only : tdd
      use MOD_SAIL, only : rsdt
      use MOD_SAIL, only : rdot
      use MOD_SAIL, only : rsodt
      use MOD_SAIL, only : rsod
      use MOD_SAIL, only : tso
      use MOD_SAIL, only : tsstoo
      use MOD_SAIL, only : rddt
      use MOD_SAIL, only : rsost
      use MOD_SAIL, only : tsd
      use MOD_SAIL, only : rsot
      use MOD_SAIL, only : rdd
      use MOD_SAIL, only : too
      use MOD_SAIL, only : rsos
      use MOD_SAIL, only : rdo
      use MOD_SAIL, only : tss
      external f2pysetupfunc
      external f2py_MOD_SAIL_getdims_rso
      external f2py_MOD_SAIL_getdims_tdo
      external f2py_MOD_SAIL_getdims_rsd
      external f2py_MOD_SAIL_getdims_tdd
      external f2py_MOD_SAIL_getdims_rsdt
      external f2py_MOD_SAIL_getdims_rdot
      external f2py_MOD_SAIL_getdims_rsodt
      external f2py_MOD_SAIL_getdims_rsod
      external f2py_MOD_SAIL_getdims_tso
      external f2py_MOD_SAIL_getdims_rddt
      external f2py_MOD_SAIL_getdims_rsost
      external f2py_MOD_SAIL_getdims_tsd
      external f2py_MOD_SAIL_getdims_rsot
      external f2py_MOD_SAIL_getdims_rdd
      external f2py_MOD_SAIL_getdims_rsos
      external f2py_MOD_SAIL_getdims_rdo
      call f2pysetupfunc(f2py_MOD_SAIL_getdims_rso,f2py_MOD_SAIL_getdims&
     &_tdo,f2py_MOD_SAIL_getdims_rsd,f2py_MOD_SAIL_getdims_tdd,f2py_MOD_&
     &SAIL_getdims_rsdt,f2py_MOD_SAIL_getdims_rdot,f2py_MOD_SAIL_getdims&
     &_rsodt,f2py_MOD_SAIL_getdims_rsod,f2py_MOD_SAIL_getdims_tso,tsstoo&
     &,f2py_MOD_SAIL_getdims_rddt,f2py_MOD_SAIL_getdims_rsost,f2py_MOD_S&
     &AIL_getdims_tsd,f2py_MOD_SAIL_getdims_rsot,f2py_MOD_SAIL_getdims_r&
     &dd,too,f2py_MOD_SAIL_getdims_rsos,f2py_MOD_SAIL_getdims_rdo,tss)
      end subroutine f2pyinitMOD_SAIL


